language: node_js
node_js:
  -"14.4.0"

install:
  - npm install newman

script:
  - node_modules/.bin/newman run tests/Postman API Testing - Trello.postman_collection.json -e Production.postman_environment.json